<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Project Euler Questions</title>
</head>
<style type="text/css">
	h1 {
		font-family:Verdana, Geneva, sans-serif;
		text-align: center;
	}
	
	#Q1{
		border:1px;
		border-style:solid;
	}
	
	#Q1 p{
		padding: 4px;
	}
	
	#Q1 form{
		float: left;
	}
	#Q2{
		border:1px;
		border-style:solid;
		margin-top:5px;
	}
	
	#Q2 p{
		padding: 4px;
	}
	
	#Q2 form{
		float: left;
	}
	#Q3{
		border:1px;
		border-style:solid;
		margin-top:20px;
	}
	
	#Q3 p{
		padding: 4px;
	}
	
	#Q3 form{
		float: left;
	}
</style>
<body>
	<h1> Project Euler </h1>
    <div id="Q1">
    	<p>If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. <br/><br/> Find the sum of all the multiples of 3 or 5 below 1000</p>
        
        <input type="text" name="Q1" id="Q1_input" value="" />
        
        <button type="text" form="Question1" value="Submit" id="Q1Button">Submit</button>

	</div>
    <div id="Q2">
    	<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10<br/> terms will be: <br/><br/><span style="text-align:center;">1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</span> <br/><br/> By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-<br/>valued terms.</p>
        <input type="text" name="Q2" id="Q2_input" value = "" />
        
        <button type= "text" form="Question2" id="Q2Button">Submit</button>

	</div>
    <div id="Q3">
    	<p>The prime factors of 13195 are 5, 7, 13 and 29 <br/><br/> What is the largest prime factor of the number 600851475143?</p>
        
        <input type="text" name="Q3" />
        
        <button type="text" form="Question3" value="Submit" id="Q3Button">Submit</button>

	</div>
    
    <script type="text/javascript">
		function answer1(){
			var total = 0;
			for(var i = 3; i < 1000; i++){
				if((i % 3 === 0) || (i % 5 === 0)){
					total += i;
				}
			}
			document.getElementById("Q1_input").value = total;
		}
		
	
		
		function answer2(){
			var a = 0, b = 1, f =1, total = 0;
			while(f <= 4000000){
				if(f % 2 == 0){
					total += f;
				}
				f = a + b;
				a = b;
				b = f;
			}
			return total;
		}
		
		document.getElementById("Q1Button").onclick = function(){
			answer1(); 
		}
		
		document.getElementById("Q2Button").onclick = function(){
			document.getElementById("Q2_input").value = answer2();
		}
		
	
	</script>
</body>
</html>
